### ISSUE TITLE
멋진 자료 감사합니다.

### ISSUE THREAD

**Issue by socialskyo** [bjrambo/randocument#2]
드디어 랜덤 위젯에서 벗어나겠네요.. 

그나저나 모듈이 두개 이상 설정 하였어도 하나의 모듈에서만 랜덤글이 나오는것 같습니다. 리포트 합니다.

**Comment by bjrambo** [comment]
@socialskyo 제 테스트환경에서 두곳의 모듈이 같이 나오는것을 확인해보았습니다.

혹시 게시글의 갯수가 어떻게 되는지 확인해보셨는지요..;ㅁ;

**Comment by socialskyo** [comment]
@bjrambo 게시물 비율문제  같습니다. 한 50번 눌러봤는데 나오더군요. ^^ 번거롭게 해드려 죄송합니다.
