### ISSUE TITLE
오.. 좋네요. 주소 끝에 위치 찾아가게...

### ISSUE THREAD

**Issue by wookho** [bjrambo/randocument#3]
옵션으로..  스킨설정에서 라던지..

특정한 위치를 찾아가게 하면 어떨까 합니다.
저희 사이트는 랜덤으로 보여주고 싶은 게시판이 사진 게시판이다보니 상단의 불필요한 부분보다 그래도 비교적 사진이 시작할 가능성이 높은 자리를 지정해 보았습니다.

location.href = "{$getlink}#ad_banner3";

이렇게 특별한 위치를 지정했는데요. 뭐 불필요한 기능일 수 도 있지만 자리를 잡고 싶은 곳에서는 옵션으로 있어도 좋을 듯한 아이디어라 제안드려 봅니다.

*PC 모바일 각각 지정이 가능하면 더 좋겟죠~

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/randocument/commit/52846e67f0f378119320f2584614d2acfd6ce868
https://github.com/bjrambo/randocument/commit/60d3e72b5795146fba971f908ff22cc476e055a7

**Comment by wookho** [comment]
방금 업데이트 된거 적용해 봤더니...
module_srls 값은 필수입니다.

요렇게 에러가 뜨네요~~
