### ISSUE TITLE
옵션 url이 모두 모바일꺼로..

### ISSUE THREAD

**Issue by wookho** [bjrambo/randocument#5]
컴에서 실행했는데 모바일쪽 옵션url 이 추가 됩니다.

**Comment by bjrambo** [comment]
rand.html 파일에
```<!--@elseif(Mobile::isFromMobilePhone())-->```
으로 수정해보세요
skins/default/rand.html 파일이에요.

**Comment by wookho** [comment]
수정할 내용이 안보여요.

**Comment by bjrambo** [comment]
커밋 할때 여러곳에서 막 푸시하다보니 서로 코드가 꼬였어요.

https://github.com/bjrambo/randocument/commit/699da9b3ad21c3c7d85a1efa29951592954b8c79
이거 확인해보면서 html템플릿파일만 한번 참고해보세요. 이 상태에서 문제가 생기는지요..

**Comment by wookho** [comment]
커밋 내용 보고 수정하니 잘 되네요.

**Comment by wookho** [comment]
어.. 이제 모바일이 이상하네요. 아무래 도 모바일쪽이 PC쪽으로 동작하는 듯 합니다.

**Comment by wookho** [comment]
그러네요. PC쪽 옵션url이 붙어버리네요..

**Comment by bjrambo** [comment]
마지막으로 수정모두마쳤어요. 다시 받아서 확인해주세요.

**Comment by wookho** [comment]
네. 이제 PC , 모바일 모두 옵션url로 지정한게 제대로 다 잘 붙어서 모두 원하는 위치를 잘 찾아가네요. 귀찮은 의견 받아주셔서 감사합니다!
